#server:
#  port: 8081
#  servlet:
#    context-path: /user
#
#spring:
#  application:
#    name: USER-SERVICE
#  datasource:
#    url: "jdbc:mysql://localhost:3306/user_service_ecommerce"
#    driverClassName: "com.mysql.cj.jdbc.Driver"
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true